### ISSUE TITLE
Channel names missing in web interface

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#1000]
https://github.com/catalinii/minisatip/blob/08c374bab421211df913a061c2fd35e7980eae54/src/pmt.c#L2255
should it be not
strlcatf(dest, max_size, pos, "%s,", pmt->name);
but it shows then all channels on the freq

**Comment by catalinii** [comment]
Fixed in master

**Comment by 9000h** [comment]
@catalinii thanks for looking in to, channel names in the status page are now correct for encrypted channels but there are no channel names shown on FTA channels

**Comment by Jalle19** [comment]
I second this, I'm getting no channel names at all with v1.2.34. @catalinii

**Comment by catalinii** [comment]
This should be fixed in the master

**Comment by Jalle19** [comment]
![Screenshot from 2022-10-20 14-52-44](https://user-images.githubusercontent.com/1106133/196941559-20861c70-8305-4583-b35b-4ef30f5beacd.png)

I still have no channel names. This is on an FTA channel.

**Comment by 9000h** [comment]
did you also use the new status.html?

**Comment by Jalle19** [comment]
Hmm, no 😄 I'll report back

**Comment by Jalle19** [comment]
Still the same issue even after updating the `html` directory contents

**Comment by Jalle19** [comment]
Not sure if this is related:

```
pmt.c: In function ‘pmt_pid_add’:
pmt.c:2221:11: warning: unused variable ‘pmt’ [-Wunused-variable]
 2221 |     SPMT *pmt = NULL;
      |           ^~~
```

I tried the latest master locally too and it has the same issue, so any problems with my production setup can be ruled out.

**Comment by 9000h** [comment]
hmm, I run it on Intel hardware maybe happened on different CPU type

**Comment by Jalle19** [comment]
Actually I'm on Intel too 🤷 I'll start bisecting my way back to the last working version.

**Comment by 9000h** [comment]
hmm, I do have no CI in my system atm

**Comment by Jalle19** [comment]
```
aacfffe44346f614baa132b89b3aa2ddfb3aac99 is the first bad commit
commit aacfffe44346f614baa132b89b3aa2ddfb3aac99
Author: Catalin Toda <catalinii@yahoo.com>
Date:   Tue Oct 4 17:09:03 2022 -0700

    Add fe= to the Web UI URL only if requested by the client #966

 html/status.html | 117 +++++++++++++++---------
 src/adapter.c    |   5 +-
 src/adapter.h    |   5 +
 src/ca.c         |  18 +++-
 src/ddci.c       |   3 +
 src/dvb.c        |  13 +--
 src/dvbapi.c     |  21 ++---
 src/pmt.c        | 271 +++++++++++++++++++++++++++++++++----------------------
 src/pmt.h        |   5 +-
 src/tables.c     |  57 +-----------
 src/tables.h     |   6 --
 src/utils.h      |   6 +-
 12 files changed, 287 insertions(+), 240 deletions(-)
 ```

**Comment by catalinii** [comment]
@Jalle19 can u check the latest master?

**Comment by Jalle19** [comment]
Yes, now it finally works! :pray:
