### ISSUE TITLE
Sky TV NZ broadcasting packets minisatip can not handle

### ISSUE THREAD

**Issue by fe31nz** [catalinii/minisatip#1215]
I subscribe to Sky TV here in New Zealand and recently they have been changing things in their broadcasts getting ready to switch to a new satellite.  A couple of days ago, they changed something that has affected a number of their muxes and now minisatip is unable to handle the packets received from channels on those muxes.  It gets packets that it thinks are too long, or packets that it sees as having CRC errors.  And the software I use to view and record the channels (MythTV and DVBViewer) is unable to tune those channels any more.

Here are a couple of examples of the error messages:

Mar 19 22:22:24 mypvr minisatip[354568]: assemble_packet: len 4098 not valid for pid 0 [38 8A 00 FF FF FF]

Mar 18 20:28:00 mypvr minisatip[4558]: pid 301 (012D) CRC failed B645CD4D != 69C1E2E5 len 82

I have been running minisatip v1.2.72~ad307a0 for some time as it was running fine so I did not need to upgrade it.  But today I also temporarily tried the git head version and saw the same errors.  I tried increasing the accepted size for pid 0 packets but while that got rid of those error messages, it did not help with getting the channels to tune.

If you go to:

[http://www2.jsw.gen.nz](url)

I have 120 second capture files of all the Sky muxes available for download.  Most of the files are about 569 Mbytes.

The old captures (2025-02-02) are all fine with minisatip.  The new ones (2025-03-19) are:

Good: 12394, 12421, 12493, 12707
Bad: 12267, 12331, 12358, 12519, 12581, 12608
Good, now broadcast from the new satellite: 12650

and the others I have not tested, so I can not say if they are good or bad.

Also available on the web server are two minisatip log files.  The minisatip.log.1 file is done with my usual log settings, and the huge (1.9 Gbyte) minisatip.log file is done with the added "-l pmt -v pmt" settings.

**Comment by catalinii** [comment]
Thanks for the report, this is indeed a bug in assemble_packet which does not take the adaptation into account, will try to fox asap

**Comment by catalinii** [comment]
hi, can u test the "test" branch and let me know if it works?

**Comment by fe31nz** [comment]
No change - the channels that worked still work, but the channels on muxes that do not work still do not work.  I have uploaded the log file from my testing.

[minisatip.log](https://github.com/user-attachments/files/19616727/minisatip.log)

In the log, I am now not seeing the "len not valid" or CRC errors any more, but the symptoms on playing a bad channel are the same - either no data at all streamed from minisatip, or only a very few bytes.  MythTV playing the bad channels in LiveTV mode reports that it was unable receive the first 2048 bytes and then stops playing.

**Comment by Jalle19** [comment]
Fixed in the latest release?

**Comment by fe31nz** [comment]
I can  not test at the moment as Sky TV NZ is currently moving all their transponders from the old Optus D2 satellite to the new Koreasat 6 satellite that has been moved to 160E to replace it.  All the D2 transponders are now sending null packets instead of channel data and I do not have the parameters for the new K6 transponders yet to be able to try them.  Hopefully in a few hours the transition will be complete and I can scan for the K6 transponders and try them.

**Comment by fe31nz** [comment]
It looks like the move to Koreasat 6 has not actually happened.  I was not getting any signal, but it turns out that was just my fat fingers not screwing home the aerial cable on my Sky set-top box.  So I compiled 1.3.48~b87a97c and started it.  Looking at the logs just now, I can see this problem is not fixed.  And also, just after 20:28 today when MythTV started four recordings at the same time via minisatip, minisatip crashed:

SUMMARY: AddressSanitizer: negative-size-param (/root/projects/minisatip/minisatip/minisatip+0x81d31) (BuildId: d071ba72071ca4159994512172fd81c91fdf3fec) in memcpy

Systemd restarted minisatip, but MythTV did not notice this and did not restart the failing recordings, so I manually restarted each of them.  The first one I restarted is on a channel that does record properly, and it started recording.  The other three are on channels affected by this problem and the recordings did not restart properly.

I have attached the gzipped 

[minisatip.log.gz](https://github.com/user-attachments/files/19732632/minisatip.log.gz)

minisatip.log file showing this.

**Comment by Jalle19** [comment]
minisatip version 1.3.48~b87a97c
```
Apr 14 20:28:01 mypvr minisatip[1995061]: =================================================================
Apr 14 20:28:01 mypvr minisatip[1995061]: ==1995061==ERROR: AddressSanitizer: negative-size-param: (size=-1)
Apr 14 20:28:01 mypvr minisatip[1995061]:     #0 0x5d40fe1e9d31 in memcpy (/root/projects/minisatip/minisatip/minisatip+0x81d31) (BuildId: d071ba72071ca4159994512172fd81c91fdf3fec)
Apr 14 20:28:01 mypvr minisatip[1995061]:     #1 0x5d40fe3c5880 in assemble_normal /root/projects/minisatip/minisatip/src/pmt.c:1461
Apr 14 20:28:01 mypvr minisatip[1995061]:     #2 0x5d40fe3c5d9f in assemble_packet /root/projects/minisatip/minisatip/src/pmt.c:1483
Apr 14 20:28:01 mypvr minisatip[1995061]:     #3 0x5d40fe3adbbb in process_filter /root/projects/minisatip/minisatip/src/pmt.c:492
Apr 14 20:28:01 mypvr minisatip[1995061]:     #4 0x5d40fe3aebc8 in process_filters /root/projects/minisatip/minisatip/src/pmt.c:535
Apr 14 20:28:01 mypvr minisatip[1995061]:     #5 0x5d40fe3c0dfb in pmt_process_stream /root/projects/minisatip/minisatip/src/pmt.c:1207
Apr 14 20:28:01 mypvr minisatip[1995061]:     #6 0x5d40fe2f77cf in process_dmx /root/projects/minisatip/minisatip/src/stream.c:1045
Apr 14 20:28:01 mypvr minisatip[1995061]:     #7 0x5d40fe2f9023 in read_dmx /root/projects/minisatip/minisatip/src/stream.c:1144
Apr 14 20:28:01 mypvr minisatip[1995061]:     #8 0x5d40fe2d6c41 in select_and_execute /root/projects/minisatip/minisatip/src/socketworks.c:864
Apr 14 20:28:01 mypvr minisatip[1995061]:     #9 0x71cacf49caa3 in start_thread nptl/pthread_create.c:447
Apr 14 20:28:01 mypvr minisatip[1995061]:     #10 0x71cacf529c3b in clone3 ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
Apr 14 20:28:01 mypvr minisatip[1995061]: 0x71cacd1a590d is located 8461 bytes inside of 376010-byte region [0x71cacd1a3800,0x71cacd1ff4ca)
Apr 14 20:28:01 mypvr minisatip[1995061]: allocated by thread T0 here:
Apr 14 20:28:01 mypvr minisatip[1995061]:     #0 0x5d40fe2572cf in __interceptor_malloc (/root/projects/minisatip/minisatip/minisatip+0xef2cf) (BuildId: d071ba72071ca4159994512172fd81c91fdf3fec)
Apr 14 20:28:01 mypvr minisatip[1995061]:     #1 0x5d40fe3499c8 in malloc1 utils/alloc.c:72
Apr 14 20:28:01 mypvr minisatip[1995061]:     #2 0x5d40fe301679 in adapter_alloc /root/projects/minisatip/minisatip/src/adapter.c:120
Apr 14 20:28:01 mypvr minisatip[1995061]:     #3 0x5d40fe42fa6f in find_dvb_adapter /root/projects/minisatip/minisatip/src/dvb.c:2002
Apr 14 20:28:01 mypvr minisatip[1995061]:     #4 0x5d40fe30180a in find_adapters /root/projects/minisatip/minisatip/src/adapter.c:138
Apr 14 20:28:01 mypvr minisatip[1995061]:     #5 0x5d40fe305e04 in init_all_hw /root/projects/minisatip/minisatip/src/adapter.c:369
Apr 14 20:28:01 mypvr minisatip[1995061]:     #6 0x5d40fe2c243c in main /root/projects/minisatip/minisatip/src/minisatip.c:2012
Apr 14 20:28:01 mypvr minisatip[1995061]:     #7 0x71cacf42a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
Apr 14 20:28:01 mypvr minisatip[1995061]:     #8 0x71cacf42a28a in __libc_start_main_impl ../csu/libc-start.c:360
Apr 14 20:28:01 mypvr minisatip[1995061]:     #9 0x5d40fe19f1f4 in _start (/root/projects/minisatip/minisatip/minisatip+0x371f4) (BuildId: d071ba72071ca4159994512172fd81c91fdf3fec)
Apr 14 20:28:01 mypvr minisatip[1995061]: Thread T17 created by T0 here:
Apr 14 20:28:01 mypvr minisatip[1995061]:     #0 0x5d40fe1c2435 in __interceptor_pthread_create (/root/projects/minisatip/minisatip/minisatip+0x5a435) (BuildId: d071ba72071ca4159994512172fd81c91fdf3fec)
Apr 14 20:28:01 mypvr minisatip[1995061]:     #1 0x5d40fe33912c in start_new_thread /root/projects/minisatip/minisatip/src/utils.c:518
Apr 14 20:28:01 mypvr minisatip[1995061]:     #2 0x5d40fe305147 in init_hw /root/projects/minisatip/minisatip/src/adapter.c:324
Apr 14 20:28:01 mypvr minisatip[1995061]:     #3 0x5d40fe30ef0b in get_free_adapter /root/projects/minisatip/minisatip/src/adapter.c:748
Apr 14 20:28:01 mypvr minisatip[1995061]:     #4 0x5d40fe2e6f3d in start_play /root/projects/minisatip/minisatip/src/stream.c:297
Apr 14 20:28:01 mypvr minisatip[1995061]:     #5 0x5d40fe2b65e8 in read_rtsp /root/projects/minisatip/minisatip/src/minisatip.c:1351
Apr 14 20:28:01 mypvr minisatip[1995061]:     #6 0x5d40fe2d6c41 in select_and_execute /root/projects/minisatip/minisatip/src/socketworks.c:864
Apr 14 20:28:01 mypvr minisatip[1995061]:     #7 0x5d40fe2c2583 in main /root/projects/minisatip/minisatip/src/minisatip.c:2017
Apr 14 20:28:01 mypvr minisatip[1995061]:     #8 0x71cacf42a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
Apr 14 20:28:01 mypvr minisatip[1995061]:     #9 0x71cacf42a28a in __libc_start_main_impl ../csu/libc-start.c:360
Apr 14 20:28:01 mypvr minisatip[1995061]:     #10 0x5d40fe19f1f4 in _start (/root/projects/minisatip/minisatip/minisatip+0x371f4) (BuildId: d071ba72071ca4159994512172fd81c91fdf3fec)
Apr 14 20:28:01 mypvr minisatip[1995061]: SUMMARY: AddressSanitizer: negative-size-param (/root/projects/minisatip/minisatip/minisatip+0x81d31) (BuildId: d071ba72071ca4159994512172fd81c91fdf3fec) in memcpy
Apr 14 20:28:01 mypvr minisatip[1995061]: ==1995061==ABORTING
```

**Comment by Jalle19** [comment]
@catalinii perhaps you could take a look at this, now that we have a clear log (negative size passed to memcpy)?

**Comment by catalinii** [comment]
i added some fixes to 2.0 related to this, so we need a new test

**Comment by Jalle19** [comment]
@fe31nz can you test again with the latest version of minisatip?

**Comment by fe31nz** [comment]
I am now running the latest version (v2.0.4~c0d1733) and so far I have not had any problems with any of the Sky channels I have tested.  However, it is likely that Sky are no longer broadcasting the packets that used to cause me problems, as when they changed over to the new Koreasat 6 satellite, they appear to have reverted back to the settings they used to use that do not cause any problems.  I am going to keep running the current version for now and see what happens with all the recordings for the next day or so.

**Comment by fe31nz** [comment]
All my Sky recordings today seem to be fine.

**Comment by Jalle19** [comment]
Please reopen this if the issue still persists 👍
