### ISSUE TITLE
Could not open demux device /dev/dvb/adapter0/demux0: Too many open files

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#155]
Hi,

After some use of minisatip with just ONE client, this message appears in the LOG:

```
Could not open demux device /dev/dvb/adapter0/demux0: Too many open files
```

And if I check the list of open handles with:

```
$ lsof -a -p [pid_of_minisatip]

COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
minisatip 6265 root  cwd    DIR    8,1     4096 1055666 /root/minisatip
minisatip 6265 root  rtd    DIR    8,1     4096       2 /
minisatip 6265 root  txt    REG    8,1   320537 1058791 /root/minisatip/minisatip
minisatip 6265 root  mem    REG    8,1  1729984  393676 /lib/x86_64-linux-gnu/libc-2.19.so
minisatip 6265 root  mem    REG    8,1    96240  267985 /usr/lib/x86_64-linux-gnu/libdvbcsa.so.1.0.1
minisatip 6265 root  mem    REG    8,1    31784  393670 /lib/x86_64-linux-gnu/librt-2.19.so
minisatip 6265 root  mem    REG    8,1   137440  393669 /lib/x86_64-linux-gnu/libpthread-2.19.so
minisatip 6265 root  mem    REG    8,1   140928  393658 /lib/x86_64-linux-gnu/ld-2.19.so
minisatip 6265 root    0w   CHR    1,3      0t0    1205 /dev/null
minisatip 6265 root    1w   REG    8,1  1762880 1058841 /root/minisatip/minisatip.log
minisatip 6265 root    2w   REG    8,1     9115 1058974 /root/minisatip/nohup.out
minisatip 6265 root    3u  IPv4 511191      0t0     UDP *:1900
minisatip 6265 root    4u  IPv4 511192      0t0     UDP 239.255.255.250:1900
minisatip 6265 root    5u  IPv4 511193      0t0     TCP *:rtsp (LISTEN)
minisatip 6265 root    6u  IPv4 511194      0t0     TCP *:http-alt (LISTEN)
minisatip 6265 root    7u  IPv4 512732      0t0     TCP debian.local:rtsp->server.local:50379 (ESTABLISHED)
minisatip 6265 root    8r   CHR  212,2      0t0    8925 /dev/dvb/adapter0/frontend0
minisatip 6265 root    9u   CHR  212,1      0t0    8842 /dev/dvb/adapter0/dvr0
minisatip 6265 root   10r   CHR  212,6      0t0  329630 /dev/dvb/adapter1/frontend0
minisatip 6265 root   11u   CHR  212,4      0t0  329621 /dev/dvb/adapter1/dvr0
minisatip 6265 root   12r   CHR 212,10      0t0  329648 /dev/dvb/adapter2/frontend0
minisatip 6265 root   13u  IPv4 511218      0t0     TCP debian.local:59583->debian.local:9000 (ESTABLISHED)
minisatip 6265 root   14u  sock    0,7      0t0  511219 can't identify protocol
minisatip 6265 root   15u   CHR  212,8      0t0  329639 /dev/dvb/adapter2/dvr0
minisatip 6265 root   16u  IPv4 512733      0t0     UDP debian.local:5500->server.local:52028
minisatip 6265 root   17u  IPv4 512734      0t0     UDP debian.local:5501->server.local:52029
minisatip 6265 root   18u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   19u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   20u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   21u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   22u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   23u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   24u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   25u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   26u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   27u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   28u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   29u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   30u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   31u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   32u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   33u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   34u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   35u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   36u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   37u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   38u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   39u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0
minisatip 6265 root   40u   CHR  212,0      0t0    8838 /dev/dvb/adapter0/demux0

```

Then I show several open handles for "/dev/dvb/adapter0/demux0".
And after this error, all new commands for tunning returns OK but no stream is received.
The only solution is restart minisatip.
It's really needed to open the demux more than one time?

Please, can you fix this?

**Comment by catalinii** [comment]
Hi,

when a new pid filter is requested for adapter0, generally this is done by opening the file /dev/dvb/adapter0/demux0 and specifying which is the pid filter that needs to be added.

The number of open files depends on how many pids you have active at that moment.

Here you log shows just 23 open pids (which is too low).

My quess is that by the time you took the output of lsof some of the pids have been cleared (and the file closed).

Can you please upload a full log of this failure ?

Thanks

**Comment by lars18th** [comment]
Hi @catalinii 

Thank you for your response!

This is using the vtuner driver for SAT>IP, and then I feel the problem is a limitation in the number of active pids. Typically, several hardware chips or drivers have a max number of active pids (around 8, 12, 16, 32 or similar). Then, this problem ins't related to minisatip. But I suggest that in case of you achieve the maximum (when the message "Too many open files" is triggered), you "free" or "reset" the tuner, because in some cases it goes to fail after then.

Another suggestion is improve the SAT>IP client mode, because using it I can forget the vtuner implementation!

Thank you for your support!
Regards.

**Comment by catalinii** [comment]
I think that is a fair suggestion, I will consider it when will look on that part of the code.

About satip we can talk in the issue opened for it.

Thanks

**Comment by catalinii** [comment]
Hi,

can you try now with the atest commit ?

Thanks

**Comment by lars18th** [comment]
@catalinii 

I'll check!

**Comment by lars18th** [comment]
Hi @catalinii ,

Very annoying: with one client the message continues, with another no problem. And the client is the same, only changes the computer where is running.

Can you do anything for increase the number of change it?

**Comment by lars18th** [comment]
Hi @catalinii ,

I found the problem: The vtuner protocol uses 30 at the fixed number of pids in the filtering list. Then you can open more than 30 pids. And in my case the client is requesting several times up to 32 pids!

I suggest to put a simple "if" and when opening a new pid in the demux and it returns an error then "close" the pidlist, it's say: don't open more pids.

You agree?

**Comment by catalinii** [comment]
I think the last time i implemented adapter close for this issue...is it not working?

**Comment by lars18th** [comment]
Hi @catalinii ,

> I think the last time i implemented adapter close for this issue...is it not working?

Yes, the current behaviour is entire close the adapter, but this closes the connection with the client... and the client then RESTART to connect, and re-try to ask for 32 pids... then when arrive to 30 pids... boom!

Please, can you add some "MAX_OPEN_PIDS" option than only "discards" to open more pids than MAX?
Thank you!

**Comment by catalinii** [comment]
BTW lars, is this happening with transponders with low signal or it happens on ones that have good signal.

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

> Is this happening with transponders with low signal or it happens on ones that have good signal.

Both! The problem is the LIMIT of the DVB Tuner... the vtuner implementation has in the internal communication protocol the limit of 30 pids. Then, because at time I continue to use the vtuner satip driver, the problem persists. I suggest to add this simple change: add a MAX_OPEN_PIDS option. I'm sure that other SAT>IP servers and DVB drivers has similiar limits, and it will be very usefull for solve compatibility troubles.

Thank you for your effort!

**Comment by catalinii** [comment]
Hi Lars,

I was looking today thru that code, did you try to change the MAX_PIDS in dvb.h from 64 to 32 to see if that will make a difference ?

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

> I was looking today thru that code, did you try to change the MAX_PIDS 
> in dvb.h from 64 to 32 to see if that will make a difference ?

I'll try. But the limit of vtuner is 30 pids (not 32). This is the real problem, because the client mode ins't fixed at time (I need to do the pcap capture for communication between minisatip and ALi SAT>IP server. You has been able to try minisatip and DVBViewer Recording Service?).

Thank you for your effort!

**Comment by lars18th** [comment]
Hi,

Because this issue is not directly related to minisatip I explain here how to circumvent it:

- If you use "vtuner-satip" with minisatip, you need to know that this virtual tuner is limited to 30 PIDS max. This limit is imposed by the "vtuner" protocol. You can see in the "vtuner.h" the definition of struct "vtuner_message" with the declaration "u16 pidlist[30]".

- If you like to use ONLY the vtuner-satip then you can modify this limit. Here how to do:

* Clone the vtuner-satip (http://code.google.com/p/satip/)

* Edit these files:
  - satip/satip_vtuner.c
  - satip/vtuner.h
  - vtuner_tweak/vtuner.h
  - vtuner_tweak/vtunerc_priv.h
* On these files replace:
  - u16 pidlist[30];  ==>  u16 pidlist[60];
  - #define MAX_PIDTAB_LEN 30  ==>  #define MAX_PIDTAB_LEN 60
    ( with this change the new limit is 60 pids, modify as you need )

* Recompile and install.

I hope this helps!

**Comment by catalinii** [comment]
Lars, should we still keep this open ?

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

I suggest to maintaining it open. Why? Because perhaps some others like to patch vtuner-satip (as me). At time, the minisatip satip-client mode continues to be unusable, so I continue using the patched vtuner-satip.

So, please, let it open. ;)

**Comment by catalinii** [comment]
I will mirror this on the forum, but I am trying to keep as less open to be focused on the issues that matter.

Thank you for the efforts you put into this.

**Comment by lars18th** [comment]
> I will mirror this on the forum

Or perhaps you like to start to use the "Wiki" part of the github server... ;)

> Thank you for the efforts you put into this.

You welcome! I'm planning to a more bigger patch for support "allpids" in vtuner-satip. However, I prefer swithing to the minisatip client mode when it will be more robust, as at time I can't discard the vtuner (in my environment it's now the only way).

**Comment by lars18th** [comment]
Thank you @catalinii ,

However, I see that you set "opts.max_pids = 20;". This is a very low value (original vtuner has a limit of 30 pids). Therefore I suggest:

- Add a parameter to set the limit of pids of a device (not all devices has the same limit).
- If not limit is set for a device, then use "unlimited" pids (some devices don't have a fixed limit).

You agree?

**Comment by catalinii** [comment]
Hi,

The value is set automatically if the message appears.

The 20 value for sh4 is a workaround for bad driver.

**Comment by lars18th** [comment]
Hi @catalinii ,

OK, but not all devices and/or drivers are equal. For example, vtuner has a limit of 30 (I created a patched version with 60). Other SAT>IP servers have limits of 16, 20, 24 or 32. Some Linux drivers has 32.

Please, can you add the option for a user configurable value?
Thank you!

**Comment by catalinii** [comment]
Hi,

Can you test with hardware that has a limit, to see how automatic setting works?

Thanks

**Comment by lars18th** [comment]
Hi @catalinii,

I'll do (in the next days). Any special to see?

Regards.

**Comment by catalinii** [comment]
If everything works good after the error.

You should see it just once (the error).
